# Yield Prediction and Profitability Analysis

This notebook covers the following tasks:
1. Data Loading and Preprocessing
2. Model Training (Regression and Classification)
3. Model Evaluation
4. Incorporating Initial Costs
5. Testing and Accuracy Check

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, classification_report, mean_squared_error, r2_score, mean_absolute_error
import joblib
import sys
sys.path.append('../../src')

In [2]:
import utils

In [3]:
df = utils.load_dataset('../../data/Processed/Data_for_model.csv')

In [4]:
df.head()

,Acre,Land_Planting,Strate_Fertilizer,Liquid_Fertilizer,Fungicide,Insecticide,Others,Area,KG,Total_Expenses,Investment,Estimated_Yield,Revenue,Profit,Is_Profitable,Cost_Per_Acre,Yield_Per_Acre
0,1,48000,156640,9872,47372,25538,9050,ampara,4971,296472,60000,838.359103,83835.910305,23835.910305,True,296472.0,4971.0
1,1,44000,158900,9932,47600,21638,9950,bakamuna,2313,292020,60000,396.034518,39603.451818,-20396.548182,False,292020.0,2313.0
2,1,46000,157250,9870,49902,23638,9050,dehiaththakandiya,1793,295710,60000,303.168645,30316.864496,-29683.135504,False,295710.0,1793.0
3,1,47000,130200,11630,48030,24600,11000,girithale,4600,272460,60000,844.160611,84416.061073,24416.061073,True,272460.0,4600.0
4,1,49200,145806,8950,49560,27650,9530,Kandakatiya,1238,290696,60000,212.937227,21293.722652,-38706.277348,False,290696.0,1238.0

In [5]:
df.tail(50)

,Acre,Land_Planting,Strate_Fertilizer,Liquid_Fertilizer,Fungicide,Insecticide,Others,Area,KG,Total_Expenses,Investment,Estimated_Yield,Revenue,Profit,Is_Profitable,Cost_Per_Acre,Yield_Per_Acre
1150,4,171147,664593,32894,198937,91086,40040,mahiyanganaya,11280,1198697,60000,470.510896,47051.089642,-12948.910358,False,299674.25,2820.0
1151,4,166196,569476,47627,187993,105159,45085,bakamuna,11850,1121536,60000,528.293341,52829.334056,-7170.665944,False,280384.00,2962.5
1152,4,173903,589015,34782,199428,86094,40085,girithale,8950,1123307,60000,398.377291,39837.729134,-20162.270866,False,280826.75,2237.5
1153,4,195477,667300,43723,202104,80748,43037,Kandakatiya,9700,1232389,60000,393.544571,39354.457075,-20645.542925,False,308097.25,2425.0
1154,4,176433,583956,56311,202947,96960,42085,medirigiriya,22050,1158692,60000,951.503937,95150.393720,35150.393720,True,289673.00,5512.5
1155,4,185812,622983,51921,196026,89181,36744,monaragala,9900,1182667,60000,418.545542,41854.554156,-18145.445844,False,295666.75,2475.0
1156,4,176940,661718,38899,192919,97721,41887,morawewa,18320,1210084,60000,756.972243,75697.224325,15697.224325,True,302521.00,4580.0
1157,4,176396,638480,43940,189453,93826,42417,nikaweratiya,15080,1184512,60000,636.549060,63654.905987,3654.905987,True,296128.00,3770.0
1158,4,193626,655831,58113,194327,82411,38850,kanthale,14150,1223158,60000,578.420776,57842.077638,-2157.922362,False,305789.50,3537.5
1159,4,195141,667371,51029,194246,108341,44465,ampara,15890,1260593,60000,630.258934,63025.893369,3025.893369,True,315148.25,3972.5
1160,4,160544,646918,51528,196237,97737,46744,dehiaththakandiya,13550,1199708,60000,564.720749,56472.074872,-3527.925128,False,299927.00,3387.5
1161,4,165416,575768,57852,186547,88008,49825,mahiyanganaya,10900,1123416,60000,485.127504,48512.750397,-11487.249603,False,280854.00,2725.0
1162,4,173986,526654,36833,190367,85929,44480,bakamuna,12120,1058249,60000,572.644056,57264.405636,-2735.594364,False,264562.25,3030.0
1163,4,184346,603892,44177,199841,99871,37461,girithale,8700,1169588,60000,371.925841,37192.584055,-22807.415945,False,292397.00,2175.0
1164,4,163182,563520,59069,197763,100315,36709,Kandakatiya,10050,1120558,60000,448.437296,44843.729642,-15156.270358,False,280139.50,2512.5
1165,4,164006,586915,45406,199213,105392,39627,medirigiriya,22750,1140559,60000,997.317982,99731.798180,39731.798180,True,285139.75,5687.5
1166,4,184926,678839,55913,188940,108717,39455,monaragala,9800,1256790,60000,389.882160,38988.216011,-21011.783989,False,314197.50,2450.0
1167,4,179737,634448,42082,203468,91678,39599,morawewa,18680,1191012,60000,784.207044,78420.704409,18420.704409,True,297753.00,4670.0
1168,4,193085,678145,39418,184151,95500,47317,nikaweratiya,15230,1237616,60000,615.295859,61529.585914,1529.585914,True,309404.00,3807.5
1169,4,178778,641811,38719,190035,100217,48642,kanthale,14600,1198202,60000,609.246187,60924.618720,924.618720,True,299550.50,3650.0
1170,4,163806,536960,36202,189024,104557,37454,ampara,16240,1068003,60000,760.297490,76029.748980,16029.748980,True,267000.75,4060.0
1171,4,161363,567029,57109,185183,109802,51742,dehiaththakandiya,13380,1132228,60000,590.870390,59087.039006,-912.960994,False,283057.00,3345.0
1172,4,179818,643128,59645,195590,94353,46166,mahiyanganaya,10600,1218700,60000,434.889636,43488.963650,-16511.036350,False,304675.00,2650.0
1173,4,199723,623809,34833,186435,115868,39582,bakamuna,11560,1200250,60000,481.566340,48156.634035,-11843.365965,False,300062.50,2890.0
1174,4,194702,602526,41569,185839,99937,39009,girithale,8750,1163582,60000,375.994128,37599.412848,-22400.587152,False,290895.50,2187.5
1175,4,167954,545730,42926,201105,107028,37524,Kandakatiya,10120,1102267,60000,459.053932,45905.393158,-14094.606842,False,275566.75,2530.0
1176,4,180783,571454,47209,191090,113900,43359,medirigiriya,21950,1147795,60000,956.181200,95618.119960,35618.119960,True,286948.75,5487.5
1177,4,193348,526842,53419,189825,114433,51770,monaragala,10050,1129637,60000,444.833163,44483.316322,-15516.683678,False,282409.25,2512.5
1178,4,181891,593624,56045,186333,111154,40173,morawewa,17950,1169220,60000,767.605754,76760.575426,16760.575426,True,292305.00,4487.5
1179,4,194625,609303,38175,193681,98386,44912,nikaweratiya,14880,1179082,60000,630.999371,63099.937070,3099.937070,True,294770.50,3720.0
1180,4,185797,524754,36005,195527,87400,40967,kanthale,14300,1070450,60000,667.943388,66794.338829,6794.338829,True,267612.50,3575.0
1181,4,191127,554949,49868,196870,106192,46584,ampara,15660,1145590,60000,683.490603,68349.060310,8349.060310,True,286397.50,3915.0
1182,4,171641,642788,51777,192411,101741,42149,dehiaththakandiya,13000,1202507,60000,540.537394,54053.739396,-5946.260604,False,300626.75,3250.0
1183,4,170398,592026,54348,191418,97714,49636,mahiyanganaya,10480,1155540,60000,453.467643,45346.764283,-14653.235717,False,288885.00,2620.0
1184,4,178007,660663,49995,195481,94813,36580,bakamuna,11830,1215539,60000,486.615403,48661.540271,-11338.459729,False,303884.75,2957.5
1185,4,190718,553942,41760,192861,111822,38729,girithale,8550,1129832,60000,378.374838,37837.483803,-22162.516197,False,282458.00,2137.5
1186,4,187298,631847,39567,201898,108837,43341,medirigiriya,22600,1212788,60000,931.737451,93173.745123,33173.745123,True,303197.00,5650.0
1187,4,161015,634672,43114,202921,115919,48671,monaragala,10200,1206312,60000,422.776197,42277.619720,-17722.380280,False,301578.00,2550.0
1188,4,178611,618786,37562,196795,108225,43933,Kandakatiya,9800,1183912,60000,413.882113,41388.211286,-18611.788714,False,295978.00,2450.0
1189,4,177156,571370,42181,185824,85783,40504,medirigiriya,22350,1102818,60000,1013.313167,101331.316681,41331.316681,True,275704.50,5587.5
1190,4,175178,523048,35828,195236,87338,40076,monaragala,9900,1056704,60000,468.437708,46843.770819,-13156.229181,False,264176.00,2475.0
1191,4,184565,607257,45884,188216,107389,49004,morawewa,18750,1182315,60000,792.935893,79293.589272,19293.589272,True,295578.75,4687.5
1192,4,171961,672284,52002,196194,98125,46557,nikaweratiya,15020,1237123,60000,607.053624,60705.362361,705.362361,True,309280.75,3755.0
1193,4,171089,528618,41670,185716,101020,36212,kanthale,13840,1064325,60000,650.177342,65017.734245,5017.734245,True,266081.25,3460.0
1194,4,198080,664449,42427,194913,97255,43838,ampara,16000,1240962,60000,644.661158,64466.115804,4466.115804,True,310240.50,4000.0
1195,4,188454,596392,55054,200119,86520,50502,dehiaththakandiya,12910,1177041,60000,548.409104,54840.910385,-5159.089615,False,294260.25,3227.5
1196,4,179557,651110,53595,198083,100210,48691,mahiyanganaya,10820,1231246,60000,439.392290,43939.229041,-16060.770959,False,307811.50,2705.0
1197,4,197878,677622,39860,193722,101239,40684,bakamuna,12140,1251005,60000,485.209891,48520.989125,-11479.010875,False,312751.25,3035.0
1198,4,195349,531081,50184,199270,115148,39610,girithale,8900,1130642,60000,393.581700,39358.169960,-20641.830040,False,282660.50,2225.0
1199,4,198322,545533,33533,187249,111463,44316,Kandakatiya,9700,1120416,60000,432.874932,43287.493217,-16712.506783,False,280104.00,2425.0

In [6]:
# One-hot encode categorical features
df_encoded = pd.get_dummies(df, columns=['Area'])

In [7]:
# Train-test split
X = df_encoded.drop(columns=['Profit', 'Is_Profitable'])
y_class = df_encoded['Is_Profitable']
y_reg = df_encoded['Profit']
X_train, X_test, y_train_class, y_test_class, y_train_reg, y_test_reg = train_test_split(X, y_class, y_reg, test_size=0.3, random_state=42)

In [8]:
# Train Regression Model
reg_model = LinearRegression()
reg_model.fit(X_train, y_train_reg)
joblib.dump(reg_model, '../../models/regression_model.pkl')

# Train Classification Model
clf_model = RandomForestClassifier()
clf_model.fit(X_train, y_train_class)
joblib.dump(clf_model, '../../models/classification_model.pkl')

['../../models/classification_model.pkl']

In [9]:
loaded_reg_model = joblib.load('../../models/regression_model.pkl')
loaded_clf_model = joblib.load('../../models/classification_model.pkl')

In [10]:
# Evaluate Regression Model
y_pred_reg = loaded_reg_model.predict(X_test)
reg_metrics = {
    'MAE': mean_absolute_error(y_test_reg, y_pred_reg),
    'MSE': mean_squared_error(y_test_reg, y_pred_reg),
    'R-squared': r2_score(y_test_reg, y_pred_reg)
}

print("Regression Model Metrics:")
print(reg_metrics)

Regression Model Metrics:
{'MAE': np.float64(5.102975819681888e-10), 'MSE': np.float64(3.352456417262843e-19), 'R-squared': 1.0}

In [11]:
# Evaluate Classification Model
y_pred_class = loaded_clf_model.predict(X_test)
print("Classification Report:")
print(classification_report(y_test_class, y_pred_class))
accuracy = accuracy_score(y_test_class, y_pred_class)
print(f"Classification Model Accuracy: {accuracy:.2f}")

Classification Report:
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       230
        True       1.00      1.00      1.00       130

    accuracy                           1.00       360
   macro avg       1.00      1.00      1.00       360
weighted avg       1.00      1.00      1.00       360

Classification Model Accuracy: 1.00

In [12]:
initial_cost = 60000  # Example initial cost

# Predict profitability with initial costs
def predict_profitability_with_initial_cost(new_data, model, initial_cost):
    new_data['Investment'] = initial_cost
    new_data_encoded = pd.get_dummies(new_data, columns=['Area'])
    missing_cols = set(X.columns) - set(new_data_encoded.columns)
    for c in missing_cols:
        new_data_encoded[c] = 0
    new_data_encoded = new_data_encoded[X.columns]
    
    y_pred = model.predict(new_data_encoded)
    new_data['Predicted_Profitability'] = y_pred
    new_data['Adjusted_Profitability'] = new_data['Predicted_Profitability'] - initial_cost
    new_data['Is_Profitable_Adjusted'] = new_data['Adjusted_Profitability'] > 0
    return new_data

#predict profit with initial cost
def predict_profit_with_initial_cost(new_data, model, initial_cost):
    new_data['Investment'] = initial_cost
    new_data_encoded = pd.get_dummies(new_data, columns=['Area'])
    missing_cols = set(X.columns) - set(new_data_encoded.columns)
    for c in missing_cols:
        new_data_encoded[c] = 0
    new_data_encoded = new_data_encoded[X.columns]
    
    y_pred = model.predict(new_data_encoded)
    new_data['Predicted_Profit'] = y_pred
    return new_data

In [16]:
new_data = pd.DataFrame({
    'Acre': [1],
    'Land_Planting': [45000],
    'Strate_Fertilizer': [150000],
    'Liquid_Fertilizer': [10000],
    'Fungicide': [50000],
    'Insecticide': [25000],
    'Others': [8000],
    'Area': ['ampara'],
    'KG': [5000],
    'Total_Expenses': [300000],
    'Investment': [60000],
    'Estimated_Yield': [800],
    'Revenue': [80000]
})
adjusted_results = predict_profitability_with_initial_cost(new_data, loaded_clf_model, initial_cost)
print("Adjusted Profitability Prediction:")
adjusted_results

profit_results = predict_profit_with_initial_cost(new_data, loaded_reg_model, initial_cost)
profit_results

Adjusted Profitability Prediction:

,Acre,Land_Planting,Strate_Fertilizer,Liquid_Fertilizer,Fungicide,Insecticide,Others,Area,KG,Total_Expenses,Investment,Estimated_Yield,Revenue,Predicted_Profitability,Adjusted_Profitability,Is_Profitable_Adjusted,Predicted_Profit
0,1,45000,150000,10000,50000,25000,8000,ampara,5000,300000,60000,800,80000,True,-59999,False,20000.0

In [14]:
# Generate random indices for the test set
np.random.seed(42)
random_indices = np.random.choice(X_test.index, size=5, replace=False)

# Select random samples from the test set
random_test_data = X_test.loc[random_indices]
random_test_labels = y_test_class.loc[random_indices]

In [15]:
# Predict on random samples
random_predictions = loaded_clf_model.predict(random_test_data)
random_accuracy = accuracy_score(random_test_labels, random_predictions)
print(f"Random Sample Accuracy: {random_accuracy:.2f}")

Random Sample Accuracy: 1.00